# Generated by Django 4.0.6 on 2022-09-20 14:59
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SRS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.assesment",),
        ),
        migrations.CreateModel(
            name="Test2",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.assesment",),
        ),
        migrations.CreateModel(
            name="Test2Q_1",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="Test3",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.assesment",),
        ),
        migrations.CreateModel(
            name="Test3Q_1",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="TestQ_1",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
    ]
