# Generated by Django 4.0.6 on 2022-08-18 10:07
import time

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("SRS", "0002_alter_question_forbidden_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="seed",
            field=models.IntegerField(
                default=time.time,
                validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
