# Generated by Django 4.0.6 on 2022-09-20 16:15
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SRS", "0002_test_test2_test2q_1_test3_test3q_1_testq_1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Q_1",
        ),
        migrations.DeleteModel(
            name="Test2Q_1",
        ),
        migrations.DeleteModel(
            name="Test3Q_1",
        ),
        migrations.DeleteModel(
            name="TestQ_1",
        ),
        migrations.CreateModel(
            name="AS91578_Q_1",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="Test2_Test2Q_1",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="Test3_Test3Q_1",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="Test_TestQ_1",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
    ]
