# Generated by Django 4.0.6 on 2022-08-18 10:08
import time

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("SRS", "0003_alter_question_seed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="last_score",
            field=models.SmallIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="seed",
            field=models.IntegerField(default=time.time),
        ),
    ]
