# Generated by Django 4.0.6 on 2022-08-18 11:29
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SRS", "0004_alter_question_last_score_alter_question_seed"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnotherQuestion",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.question",),
        ),
        migrations.CreateModel(
            name="AS91392",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.assesment",),
        ),
        migrations.CreateModel(
            name="OtherQuestion",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.question",),
        ),
    ]
