# Generated by Django 4.0.6 on 2022-09-29 11:36
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("SRS", "0005_delete_as91578_q_1_delete_test2_q_1_delete_test3_q_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assesment",
            name="attempts",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
