# Generated by Django 4.0.6 on 2022-09-29 11:37
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SRS", "0006_assesment_attempts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assesment",
            name="attempts",
        ),
    ]
