# Generated by Django 4.0.6 on 2022-10-15 22:28
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SRS", "0008_assesment_last_accessed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AS2_Q_1",
        ),
        migrations.DeleteModel(
            name="AS3_Q_1",
        ),
        migrations.DeleteModel(
            name="AS4_Q_1",
        ),
        migrations.DeleteModel(
            name="AS90521_Q_1",
        ),
        migrations.DeleteModel(
            name="AS91578",
        ),
        migrations.DeleteModel(
            name="Test",
        ),
        migrations.DeleteModel(
            name="Test2",
        ),
        migrations.DeleteModel(
            name="Test3",
        ),
        migrations.CreateModel(
            name="AS91391",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.assesment",),
        ),
        migrations.CreateModel(
            name="AS91391_Q_1",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91524",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.assesment",),
        ),
        migrations.CreateModel(
            name="AS91524_Q_1",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91577",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.assesment",),
        ),
        migrations.CreateModel(
            name="AS91577_Q_1",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
    ]
