# Generated by Django 4.0.6 on 2022-10-16 12:52
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SRS", "0009_delete_as2_q_1_delete_as3_q_1_delete_as4_q_1_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AS91391",
        ),
        migrations.DeleteModel(
            name="AS91391_Q_1",
        ),
        migrations.CreateModel(
            name="AS91524_Q_10",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91524_Q_11",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91524_Q_12",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91524_Q_13",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91524_Q_2",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91524_Q_3",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91524_Q_4",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91524_Q_5",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91524_Q_6",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91524_Q_7",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91524_Q_8",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91524_Q_9",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91577_Q_2",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91577_Q_3",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91577_Q_4",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91577_Q_5",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
        migrations.CreateModel(
            name="AS91577_Q_6",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("SRS.qaa",),
        ),
    ]
