# Generated by Django 4.0.6 on 2022-10-16 13:53
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SRS", "0010_delete_as91391_delete_as91391_q_1_as91524_q_10_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AS91524_Q_10",
        ),
        migrations.DeleteModel(
            name="AS91524_Q_11",
        ),
        migrations.DeleteModel(
            name="AS91524_Q_12",
        ),
        migrations.DeleteModel(
            name="AS91524_Q_13",
        ),
        migrations.DeleteModel(
            name="AS91524_Q_6",
        ),
        migrations.DeleteModel(
            name="AS91524_Q_7",
        ),
        migrations.DeleteModel(
            name="AS91524_Q_8",
        ),
        migrations.DeleteModel(
            name="AS91524_Q_9",
        ),
    ]
