# Generated by Django 4.0.6 on 2022-10-16 23:48
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SRS", "0011_delete_as91524_q_10_delete_as91524_q_11_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AS91577_Q_6",
        ),
    ]
